
debug: true

host: "www.yingyj.com"

author: "yingyujia <admin@yingyj.com>"

database:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root@127.0.0.1:3306/blog?charset=utf8mb4&use_unicode=0"
  SQLALCHEMY_TRACK_MODIFICATIONS: true

logging:
  level: 30 # WARN=30,ERROR=40,FATAL=50
